# Generated by Django 5.0.4 on 2024-04-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_remove_token_created_at_remove_token_refresh_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
